#!/bin/bash

#copied from the AbleC deep-clean script
find . -name "*~" -delete
find . -name "build.xml" -delete
find . -name "*.copperdump.html" -delete
find . -name "Parser*.html" -delete

#remove everything in generated but README.md
find generated/* -not -name 'README.md' -delete

rm -f *.jar
