#!/bin/bash

#copied from the AbleC deep-clean script
find . -name "*~" -delete
find . -name "build.xml" -delete
find . -name "*.copperdump.html" -delete
find . -name "Parser*.html" -delete

rm -rf generated/*
rm *.jar
