#!/bin/bash

#Create a tar for distribution

set -eu

./build

ST=extensibella-dist

ln -s . $ST

tar -zcvf sterling.tar.gz \
    "--exclude=*~" \
    $ST/build \
    $ST/deep-clean \
    $ST/docs \
    $ST/generated/README.md \
    $ST/grammars \
    $ST/ide \
    $ST/install \
    $ST/LICENSE \
    $ST/README.md \
    $ST/stdLib \
    $ST/sterling \
    $ST/sterling.jar


rm $ST
