#!/bin/bash

#Create a tar for distribution

set -eu

./build

cd ..

tar -zcvf sterling/sterling.tar.gz \
    "--exclude=*~" \
    sterling/build \
    sterling/deep-clean \
    sterling/docs \
    sterling/generated/README.md \
    sterling/grammars \
    sterling/ide \
    sterling/install \
    sterling/LICENSE \
    sterling/README.md \
    sterling/stdLib \
    sterling/sterling \
    sterling/sterling.jar
