#!/bin/bash

THIS_SCRIPT=$(readlink -f "${BASH_SOURCE[0]}")

export SOS_HOME=${THIS_SCRIPT/\/sos-ext}
export SOS_GRAMMARS=${SOS_HOME}/grammars/
export SOS_GENERATED=${SOS_HOME}/generated/

JAR="$SOS_HOME/sos-ext.jar"


if [ ! -f "$JAR" ]; then
    echo "Couldn't find the jar to execute; aborting"
    exit 2
fi

java -jar "$JAR" "$@"

