#!/bin/bash

# (cd ../.. && ./deep-clean && ./build --clean --mwda)
echo "---------------------------------"
echo "Build completed."
echo "---------------------------------"
sterling --ocaml --silver-concrete -I .. $@ imp_executable:host
java -jar imp_executable.host.jar examples/hello.imp