#!/bin/bash

# sterling $@ -I .. imp:composed
(cd ../.. && ./build)
echo "---------------------------------"
echo "Build completed."
echo "---------------------------------"
sterling --ocaml --silver-concrete -I .. $@ imp_executable:host
